print('Welcome to the tip calculator.')
print('What was the total bill? $')
total_bill = float(input())
print('How many people to split the bill?')
people = int(input())
print('What percentage tip would you like to give? 10, 12 or 15?')
percentage = int(input())
tip = round(total_bill * (1 + percentage / 100) / people, 2)
print(f'Each person should pay: ${tip}')
